theme: jekyll-theme-slate
title: Draco
description: Desktop Environment
show_downloads: true
github:
  zip_url: https://sourceforge.net/projects/draco/files/live/draco-live-20190520.iso/download
  tar_url: https://github.com/rodlie/draco/releases
